### ISSUE TITLE
Topic Controler not created in 0.4.0

### ISSUE THREAD

**Issue by prune998** [strimzi/strimzi#440]
Hi,

I had a working config to create a cluster + topics using 0.2.0, and trying to move to 0.4.0-rc1 the Topic controler is not started anymore.

Cluster configmap : 
```
apiVersion: v1
data:
  kafka-config: |-
    {
      "num.partitions": 1,
      "num.recovery.threads.per.data.dir": 1,
      "default.replication.factor": 1,
      "offsets.topic.replication.factor": 1,
      "transaction.state.log.replication.factor": 1,
      "transaction.state.log.min.isr": 1
    }
  kafka-healthcheck-delay: "15"
  kafka-healthcheck-timeout: "5"
  kafka-image: strimzi/kafka:0.4.0-rc1
  kafka-metrics-config: |-
    {
      "lowercaseOutputName": true,
      "rules": [
          {
            "pattern": "kafka.server<type=(.+), name=(.+)PerSec\\w*><>Count",
            "name": "kafka_server_$1_$2_total"
          },
          {
            "pattern": "kafka.server<type=(.+), name=(.+)PerSec\\w*, topic=(.+)><>Count",
            "name": "kafka_server_$1_$2_total",
            "labels":
            {
              "topic": "$3"
            }
          }
      ]
    }
  kafka-nodes: "1"
  kafka-storage: '{ "type": "ephemeral" }'
  topic-operator-config: '{ }'
  zookeeper-healthcheck-delay: "15"
  zookeeper-healthcheck-timeout: "5"
  zookeeper-image: strimzi/zookeeper:0.4.0-rc1
  zookeeper-metrics-config: |-
    {
      "lowercaseOutputName": true
    }
  zookeeper-nodes: "1"
  zookeeper-storage: '{ "type": "ephemeral" }'
kind: ConfigMap
metadata:
  labels:
    strimzi.io/kind: cluster
    strimzi.io/type: kafka
  name: kafka-cluster
```

and the topic Configmap : 

```
apiVersion: v1
data:
  config: |-
    {
      "cleanup.policy": "compact"
    }
  name: alertevent
  partitions: "1"
  replicas: "1"
kind: ConfigMap
metadata:
  labels:
    strimzi.io/cluster: kafka-cluster
    strimzi.io/kind: topic
  name: alertevent
```

Am I missing something ?
