### ISSUE TITLE
PersistentVolumes not all created when using custom StorageClass

### ISSUE THREAD

**Issue by sneko** [strimzi/strimzi#477]
Hi!

I'm facing a weird issue, I try to use my own StorageClass that is defined like this:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slow
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  type: pd-standard
  zones: us-central1-a, us-central1-b
```

But when applying my cluster.yaml which specifies:
```
  kafka-storage: |-
    { "type": "persistent-claim", "class": "slow", "size": "1Gi", "delete-claim": false }

  zookeeper-storage: |-
    { "type": "persistent-claim", "class": "slow", "size": "1Gi", "delete-claim": false }
```

Something goes totally randomly, just a part of all PersistentVolumes are created. That means my pods are stuck because PVC are in Pending status since there is no PV to link.

First time it was 2/3 of all that were created, second time just 1/3 😭 

Didn't find anything about this issue so I tried to use the default StorageClass by removing this parameter:
```
  kafka-storage: |-
    { "type": "persistent-claim", "size": "1Gi", "delete-claim": false }

  zookeeper-storage: |-
    { "type": "persistent-claim", "size": "1Gi", "delete-claim": false }
```

And it works immediately well... I don't understand at all. May my StorageClass is not well-made? However it works well for other tools like ElasticSearch, Jenkins...

Does someone has experienced this issue or could help me figure it out what's the origin of the problem?

Thank you!
