### ISSUE TITLE
Add support for JBOD storage

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi#482]
Users should be able to configure Kafka clusters with JBOD storage - setting up multiple disks for a single node which will be configured in Kafka to be used in parallel.

**Comment by ppatierno** [comment]
Today we have the `storage` property which enables to define the storage to use (persistent or ephemeral).
We have just one related `data` volume (different PVCs in case of persistent, i.e. `data-my-cluster-kafka-BROKER_ID`) and the mount path as `/var/lib/kafka`. The `log.dirs` in Kafka is configured using that one + "kafka-log-BROKER_ID".

The proposal for adding JBOD support is about a new storage type (`jbod` ?) with a collection of storage(s).

```yaml
apiVersion: kafka.strimzi.io/v1alpha1
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    # ....
    storage:
      type: jbod
      storages:
      - type: persistent-claim
        size: 100Gi
        deleteClaim: false
      - type: persistent-claim
        size: 100Gi
        deleteClaim: false
      - type: ephemeral
      # ...
```

Every storage will have its own `data-X` volume and where applicable (persistent), the brokers will have PVCs as `data-X-my-cluster-kafka-BROKER_ID` and a corresponding mount path as `/var/lib/kafka/data-X-kafka-log-BROKER_ID`.
The `log.dirs` in the Kafka configuration will be changed accordingly as a list of this kind of mount paths.

I have a couple of open questions:

- Does it make sense to allow mixing ephemeral with persistent-claim in a JBOD configuration? I don't think so even if I am not sure that it's worth to limit the user but I don't see a real use case for mixing.
- Could be useful adding a `name` property to the `storage` to allow the user to configure more friendly names instead of using an X index for them? As we don't allow this kind of change today just using `data` (and derived names) I think that it's fine living with `data-X` with this proposal.

@scholzj @tombentley @stanlyDoge @kyguy wdyt?

**Comment by tombentley** [comment]
> `storages`

That's really quite an awkward plural, but I'm not sure there's anything better. Would something like `volumes` or `disks`, or `storageVolumes` be confusing?

> Does it make sense to allow mixing ephemeral with persistent-claim in a JBOD configuration? 

What benefit do you think preventing it would bring? In general I think it's a mistake artificially limiting something like this just because we don't have a use case. 

One thing you _would_ need to prevent was one of the `storages` itself having type `jbod`.

> Could be useful adding a name property to the storage to allow the user to configure more friendly names instead of using an X index for them?

If we think people will attach semantics to the different storages (e.g. configure one set of partitions on one disk and some other set on some other disk for reasons beyond the performance improvements from having independent disks) then probably allowing them a way to name them would make sense.

Do you know if the log dir gets persisted anywhere in ZK? I'm pretty sure it doesn't, but it's worth checking because it might stand to interfere with the user reordering the list of storages.

**Comment by ppatierno** [comment]
> One thing you would need to prevent was one of the storages itself having type jbod.

We should also check that the `jbod` type is not using for configuring the storage in the Zookeeper spec.

**Comment by ppatierno** [comment]
Actually, providing the possibility to assign a `name` to a `storage` could drive to some problems.

For example, today we don't allow to move from ephemeral to persistent and vice versa and if you look at the code in the `StatefulSetOperator.revertStorageChanges`, the way we identify which volumes should be "reverted" is the fixed `VOLUME_NAME` (which is "data"); there are other volumes related to configmap and secret we don't have to touch there.
If we allow users to specify a name we are going to be in trouble in this case.
The user could change the storage name and then the type and we don't have enough information in the current and desired statefulset to do the revert; in the current we are not able to distinguish which volume is for the log messages and the other ones (well we could excluding the other ones but ... ).

I am really thinking that just moving from `data` to `data-X` so having a sort of `startingWith` rule could be the simpler solution for us. @tombentley wdyt?

**Comment by ppatierno** [comment]
Another problem is what kind of changes we are going to allow to do.
Today we don't allow to change type and/or size in storage, actually the above `revertStorageChanges` comes into play as soon as a change happens in the VolumeClaimTemplate during a SS diff.

With current behaviour we are going to not allow ephemeral (E) to persistent (P) or jbod (J) or viceversa but we should support the possibility for a user to update a J storage adding another volume but, if it's a P one, it drives in a change to the VolumeClaimTemplate as well so the reverting comes into play again.
Because using J storage is useful for increasing the space adding a new disk we have to support that for sure.

Btw slightly related to the previous comment I would stick with fixed names in order to avoid a new crazy variable here.

**Comment by ppatierno** [comment]
Or latest thought is about using `data` as a prefix if user specify a `name` for a storage, so ...

* `name` empty --> volume name or volume claim template (for persistent) is `data` or `data-X` (for more volumes without name in JBOD storage)
* `name` not empty -> volume name or volume claim template (for persistent) is `data-<name>`

**Comment by ppatierno** [comment]
Another tought to add ... is about adding an annotation in the SS for storing the storage-type because actually we are distinguishing ephemeral from persistent just checking if the volume claim template is empty (ephemeral) or not (persistent). Adding jbod it could be useful having an annotation defining the storage-type.

**Comment by ppatierno** [comment]
After discussing with @tombentley the idea is about adding the `name` property to the current `storage` CRD in order to allow the user to identify the disks/storage. The `name` property has to be mandatory (in this case we cannot break the API so we cannot make it mandatory at CRD level but we should document it and raising an exception at CO level if it's not set).

Regarding updating the `storage`, the user cannot change the `name` (as we don't allow to do for `size` and `type`).

Naming E (ephemeral type), P (persistent-claim type) and J (JBOD type), we have following scenarios:

- P --> J [P] : it's possible but user cannot change `name` or `size`. He is changing the `type` from P to J. So P as to be the same.
- J [P] --> P : should be possible as before
- J [P1] --> J [P1 P2 E1 E2] : it'a about adding a new storage (P2, E1 and E2). It's possible but the user has to preserve all the information from the first one P1.
- J [P1 P2 E1] --> J [E1 P1 P2] : it's possible reordering.

Removing from J is not allowed.

Another proposal could be to make `Kafka.spec.kafka.storage` deprecated and creating a new property as `Kafka.spec.kafka.logs` as a list of `NamedStorage` where `name` is mandatory by nature. In this case we don't have the need for a new J type anymore but use can just listing E and P.

```yaml
apiVersion: kafka.strimzi.io/v1alpha1
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    # ....
    logs:
      - name: my-storage-1
        type: persistent-claim
        size: 100Gi
        deleteClaim: false
      - name: my-storage-2
        type: persistent-claim
        size: 200Gi
        deleteClaim: false
      - name: my-storage-3
        type: ephemeral
      # ...
```

Upgrading an old YAML to a new one using `logs` having PV and PVC still working means, for the user, just using `data` as name (which is the default one for the single storage we are supporting today).

@tombentley @scholzj @stanlyDoge @kyguy feedback are really welcome to avoid wasting time to implementing in some way without have a sort of quorum in the team :-)

**Comment by ppatierno** [comment]
> I kind of like the original idea with storage type jbod. I'm just not sure we really need to support different volume types on single broker - that could save us the effort of having the type and class repeat multiple times.

Do you mean that under storage type JBOD, all the volumes are persistent-claim? And the only thing we need to specify is the size?

> The names are IMHO good - we can prefix them to make sure it will nto create any conflicts. I used the same in Kafka Connect for the mounted secret / config map volumes.

In the example, the my-storage names are provided by the users so what do you mean by "The names are IMHO good"? Yeah my proposal was also to add a prefix to the name. Can you provide the example on what you mentioned about Kafka Connect please?

**Comment by scholzj** [comment]
> Do you mean that under storage type JBOD, all the volumes are persistent-claim? And the only thing we need to specify is the size?

```yaml
apiVersion: kafka.strimzi.io/v1alpha1
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    # ....
    storage:
      type: jbod
      deleteClaim: false
      storageClass: ssd
      volumes:
      - name: my-storage-1
        size: 100Gi
      - name: my-storage-2
        size: 200Gi
      # ...
```

> In the example, the my-storage names are provided by the users so what do you mean by "The names are IMHO good"? Yeah my proposal was also to add a prefix to the name. Can you provide the example on what you mentioned about Kafka Connect please?

To make sure the volume names by user do not conflict with our volume names, you just prefix the names. E.g. for a volume with name specified by user as `my-storage-1`, you would create the volume in the YMAL as `kafka-logs-my-storage-1`. This is what I used in Kafka Connect to make sure the volumes with the external configuration don't override the user modules etc.

**Comment by tombentley** [comment]
If the `storageClass` has to be set on the top-level (can't be overridden in individual volumes) wouldn't that make it impossible to migrate from one storage class to another? Presumably, eventually, someone will want to do that. If they can build JBOD from different storage classes then such a migration would be possible by reassigning replicas to the new (different `storageClass`) volumes.

**Comment by tombentley** [comment]
What I mean by "migrate from one storage class to another" is moving that data from storage of one class to storage of a different class, by moving the log segments via `AdminClient` from log dir on the old storage class to log dir on the new storage class.

**Comment by scholzj** [comment]
I thought that we discuss that we will keep supporting only adding of new storage. I think that deleting the volumes like this could be quite dangerous. I'm not sure we should support that without an additional support to actually check from the CO that everything had been moved.

That said, it is probably valid point to make the API more future proof. So I agree that we might want to keep the storage class within the volume object.

**Comment by ppatierno** [comment]
At this point I would use the YAML I provided, having all configuration parameters in every single volume (so it's also possible to have persistent-claim and ephemeral volumes).

Regarding the name: @scholzj do you remember that we had a problem with long name volumes and we moved to use `data`? I remember something like this, or?

**Comment by ppatierno** [comment]
> Which of the YAMLs you provided you mean? :-o I think you provided two of them.

I was referring to the last one with a sort of "final" proposal.

```
apiVersion: kafka.strimzi.io/v1alpha1
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    # ....
    storage:
      type: jbod
      deleteClaim: false
      storageClass: ssd
      volumes:
      - name: my-storage-1
        size: 100Gi
      - name: my-storage-2
        size: 200Gi
      # ...
```

> Yes, I think that was about the names of the PersistenVolumeClaims if I recall correctly.

So it's a problem then. because today the PVC name is `data`-<statefulsetname>-<podid> (the latest two fields build the pod name). Using naming on volumes with a prefix we could have `kafka-logs-my-storage-1-<statefulsetname>-<podid> which is for sure too long.

> I do not think NamedStorage has any real meaning - it has of course some name even before this feature and the aspect of naming the volumes is not the important part.

I think that naming wasn't so important before JBOD due to the fact that we have just one name `data`. Now we need to distinguish volumes in some way.

**Comment by scholzj** [comment]
> I think that naming wasn't so important before JBOD due to the fact that we have just one name data. Now we need to distinguish volumes in some way.

But the name it self is not important, or? It is just a handle to be able to work with it and diff it. If the names would be just indexes, it would work equally well. It is just less intuitive to enter them. 

For example:

```yaml
apiVersion: kafka.strimzi.io/v1alpha1
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    # ....
    storage:
      type: jbod
      deleteClaim: false
      storageClass: ssd
      volumes:
      - name: "1"
        size: 100Gi
      - name: "2"
        size: 200Gi
      # ...
```

I'm not sure I have seen similar numbering pattern anywhere else in Kubernetes. But technically this would work for us fine.
